/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StorageSplatRouteImport } from './routes/storage/$'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageSplatRoute = StorageSplatRouteImport.update({
  id: '/storage/$',
  path: '/storage/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/users': typeof UsersRoute
  '/storage/$': typeof StorageSplatRoute
}
export interface FileRoutesByTo {
  '/users': typeof UsersRoute
  '/storage/$': typeof StorageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/users': typeof UsersRoute
  '/storage/$': typeof StorageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/users' | '/storage/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/users' | '/storage/$'
  id: '__root__' | '/users' | '/storage/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UsersRoute: typeof UsersRoute
  StorageSplatRoute: typeof StorageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/$': {
      id: '/storage/$'
      path: '/storage/$'
      fullPath: '/storage/$'
      preLoaderRoute: typeof StorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  UsersRoute: UsersRoute,
  StorageSplatRoute: StorageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
